### ISSUE TITLE
Todo: ability to order by upcoming dates

### ISSUE THREAD

**Issue by whatjoesays** [nottinghamdigital/nottinghamdigital.github.io#17]
On the redesign I added moment.js to reformat the dates which the API sends.

I've opened [an issue](https://github.com/pavlakis/notts-digital/issues/11) with @pavlakis to have the dates arrive in a portable format instead.

When that is available, I will be adding a "sort by" that does the current calendar order (i.e. week 1, week2, ...) and a new nearest to today order (e.g. it's Dec 7, so #NottTechParty on Dec 8 should be top).

**Comment by sdh100shaun** [comment]
@pavlakis  added the functionality for nearest by date , I amended the js and raised a pull request  https://github.com/nottinghamdigital/nottinghamdigital.github.io/pull/25 which currently automatically sorts by date, although this could be triggered by button (eventApi.sortByDate)
