### ISSUE TITLE
Remove or reduce local caching of event dates

### ISSUE THREAD

**Issue by jhigman** [nottinghamdigital/nottinghamdigital.github.io#34]
The event date data is cached in local storage for 24 hours - this seems a long time, especially if bad data has been cached.

Now that the event lookup api has it's own caching, could we remove - or at least reduce - this layer of caching?

**Comment by sdh100shaun** [comment]
Fixed in https://github.com/nottinghamdigital/nottinghamdigital.github.io/pull/37
