### ISSUE TITLE
Add Ministry of Testing instead of Notts Test

### ISSUE THREAD

**Issue by jhigman** [nottinghamdigital/nottinghamdigital.github.io#39]
New meetup group : https://www.meetup.com/ministry-of-testing-nottingham/

Replaces NottsTest.

**Comment by sdh100shaun** [comment]
Does this require a rename on the frontend or just the API?

**Comment by jhigman** [comment]
I think it needs both - up until now, the NottsTest entry has been using a shared group on meetup.com  (SoftwareTestingClub) and matching specific entries(#NottsTest). Now it's got it's own meetup url, and a new name.

**Comment by sdh100shaun** [comment]
OK can roll into that open PR I have
