### ISSUE TITLE
Enable https for the site 

### ISSUE THREAD

**Issue by sdh100shaun** [nottinghamdigital/nottinghamdigital.github.io#49]
Enable https for the site .. if letsencrypt doesn't work and a cert is needed happy to contribute.

**Comment by nottinghamdigital** [comment]
OK, looks like the way to do it is to use Cloudflare to front the domain, and that can take care of the https aspects (as well as providing CDN capabilities and DDOS protection, not that those are likely to be important..). I'll see if I can get it set up.

**Comment by nottinghamdigital** [comment]
I've setup Cloudflare to front the domain, with a page rule to always redirect to https.

Cloudflare pulls content from the github pages site, but applies it's own (shared) https certificate. Apparently that works across all modern browsers using SNI (https://www.digicert.com/ssl-support/apache-secure-multiple-sites-sni.htm)

Let me know if anyone reports problems..

**Comment by sdh100shaun** [comment]
Fantastic ... works for me ... allows us to use a service worker now and add notifications 👍
