### ISSUE TITLE
Security vulnerabilities in sshpk and lodash

### ISSUE THREAD

**Issue by jhigman** [nottinghamdigital/nottinghamdigital.github.io#72]
Known moderate severity security vulnerability detected in sshpk < 1.13.2defined in package-lock.json.
--
package-lock.json update suggested: sshpk ~> 1.13.2.

Known high severity security vulnerability detected in lodash <4.17.5 defined in package-lock.json.
--
package-lock.json update suggested: lodash ~> 4.17.5.

**Comment by sdh100shaun** [comment]
has this been addressed by this https://github.com/nottinghamdigital/nottinghamdigital.github.io/commit/42a57a2323b22d4a9d29fa69c2013c550d8cfd47

**Comment by jhigman** [comment]
I think possibly the updates do fix all the vulnerabilities, but I'm not quite familiar enough with the way dependencies are managed in the package-lock.json files.. Is the version shown in package-lock.json the only one that gets loaded (regardless of what other versions might appear in package.json in other modules that are dependencies?)
And can there be more than one version in the lock file?

**Comment by jhigman** [comment]
yes fixed i think
