### ISSUE TITLE
Security vulnerability in randomatic

### ISSUE THREAD

**Issue by jhigman** [nottinghamdigital/nottinghamdigital.github.io#74]
@nottinghamdigital  nottinghamdigital/nottinghamdigital.github.io
Known low severity security vulnerability detected in randomatic < 3.0.0 defined in package-lock.json.
package-lock.json update suggested: randomatic ~> 3.0.0.

**Comment by sdh100shaun** [comment]
has this been addressed by this [42a57a2](https://github.com/nottinghamdigital/nottinghamdigital.github.io/commit/42a57a2323b22d4a9d29fa69c2013c550d8cfd47)

**Comment by jhigman** [comment]
yes fixed
