### ISSUE TITLE
Security vulnerability in cryptiles

### ISSUE THREAD

**Issue by jhigman** [nottinghamdigital/nottinghamdigital.github.io#76]
Known high severity security vulnerability detected in cryptiles < 4.1.2defined in package-lock.json.
--
package-lock.json update suggested: cryptiles ~> 4.1.2.

**Comment by sdh100shaun** [comment]
has this been addressed by this [42a57a2](https://github.com/nottinghamdigital/nottinghamdigital.github.io/commit/42a57a2323b22d4a9d29fa69c2013c550d8cfd47)

**Comment by jhigman** [comment]
yes fixed
